### ISSUE TITLE
main js file + package.json with start script and engine entries

### ISSUE THREAD

**Issue by vitordino** [Iemankm/M7_Ex01#1]
we’re missing a main js file, like:

> index.js
```js
console.log('hello world')
```

would be nice to see a package json with at least a `start` script and the engines entry on `package.json`:

> package.json
```json
{
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": "^14",
    "npm": "8.3.1"
  }
}
```

**Comment by Iemankm** [comment]
I do have those, I must have forgotten to include them.

**Comment by vitordino** [comment]
that’s correct now
